services:
  # Production API
  dp_production_v0.1:
    image: ghcr.io/daoquangtung2411/maio_assignment3/diabetes_progression:v0.1.7
    container_name: diabetes_progression_production_v0.1
    ports:
      - "8386:8386"
    restart: unless-stopped
    environment:
      - ENV=production
    volumes:
      - ./logs:/app/logs
  
  dp_retrain_v0.1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diabetes_progression_retrain_v0.1
    ports:
      - "8386:8386"
    volumes:
      - .:/app
    environment:
      - ENV=developement
    command: bash -c "python scripts/train_v0_1.py && uvicorn scripts.api_v0_1:app --host 0.0.0.0 --port 8386"
